"""all dbs fix

Revision ID: 03ff808bc9cc
Revises: 3ea391817900
Create Date: 2025-05-05 11:51:58.187350

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '03ff808bc9cc'
down_revision: Union[str, None] = '3ea391817900'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('stamps', sa.Column('photo_url', sa.String(), nullable=False))
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('stamps', 'photo_url')
    # ### end Alembic commands ###
