"""cascade for collector2

Revision ID: 233a8136787b
Revises: 0724d2904ae7
Create Date: 2025-05-17 12:17:22.193205

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '233a8136787b'
down_revision: Union[str, None] = '0724d2904ae7'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint('collectors_user_id_fkey', 'collectors', type_='foreignkey')
    op.create_foreign_key(None, 'collectors', 'users', ['user_id'], ['id'], ondelete='CASCADE')
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint(None, 'collectors', type_='foreignkey')
    op.create_foreign_key('collectors_user_id_fkey', 'collectors', 'users', ['user_id'], ['id'])
    # ### end Alembic commands ###
