"""photo forcollection

Revision ID: d29482e99afa
Revises: ef0eed0334d8
Create Date: 2025-05-15 19:23:58.758396

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'd29482e99afa'
down_revision: Union[str, None] = 'ef0eed0334d8'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('collections', sa.Column('photo_url', sa.String(), nullable=False))
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('collections', 'photo_url')
    # ### end Alembic commands ###
