"""collector db null

Revision ID: ef0eed0334d8
Revises: 03ff808bc9cc
Create Date: 2025-05-13 15:41:58.150760

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'ef0eed0334d8'
down_revision: Union[str, None] = '03ff808bc9cc'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column('collectors', 'country',
               existing_type=sa.VARCHAR(length=50),
               nullable=True,
               existing_server_default=sa.text("'Россия'::character varying"))
    op.alter_column('collectors', 'phone_number',
               existing_type=sa.VARCHAR(length=20),
               nullable=True)
    op.alter_column('collectors', 'first_name',
               existing_type=sa.VARCHAR(length=50),
               nullable=True)
    op.alter_column('collectors', 'last_name',
               existing_type=sa.VARCHAR(length=50),
               nullable=True)
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column('collectors', 'last_name',
               existing_type=sa.VARCHAR(length=50),
               nullable=False)
    op.alter_column('collectors', 'first_name',
               existing_type=sa.VARCHAR(length=50),
               nullable=False)
    op.alter_column('collectors', 'phone_number',
               existing_type=sa.VARCHAR(length=20),
               nullable=False)
    op.alter_column('collectors', 'country',
               existing_type=sa.VARCHAR(length=50),
               nullable=False,
               existing_server_default=sa.text("'Россия'::character varying"))
    # ### end Alembic commands ###
