@startuml
start

partition "Просмотр марок" {
  :Пользователь просматривает список марок;
  if (Выбрать марку?) then (да)
    :Просмотр деталей марки;
  else (нет)
    :Продолжить без выбора;
  endif
}

partition "Управление марками" {
  if (Создать новую марку?) then (да)
    :Ввод данных новой марки;
    :Сохранение марки;
  else (нет)
    :Пропустить создание;
  endif

  if (Редактировать марку?) then (да)
    :Изменение данных марки;
    :Сохранение изменений;
  else (нет)
    :Пропустить редактирование;
  endif

  if (Удалить марку?) then (да)
    :Подтверждение удаления;
    :Удаление марки;
  else (нет)
    :Пропустить удаление;
  endif
}

stop
@enduml
