@startuml
|Клиент|
start

:Просмотр коллекций;
if (Выбрать коллекцию?) then (да)
  :Просмотр деталей коллекции;

  if (Создать новую коллекцию?) then (да)
    |Коллекция|
    :Ввод данных коллекции;
    :Сохранение коллекции;
    |Клиент|
  endif

  if (Редактировать коллекцию?) then (да)
    |Коллекция|
    :Изменение данных коллекции;
    :Сохранение изменений;
    |Клиент|
  endif

  if (Удалить коллекцию?) then (да)
    |Коллекция|
    :Подтверждение удаления;
    :Удаление коллекции;
    |Клиент|
  endif
endif

:Просмотр марок;
if (Выбрать марку?) then (да)
  :Просмотр деталей марки;

  if (Создать новую марку?) then (да)
    |Марка|
    :Ввод данных марки;
    :Сохранение марки;
    |Клиент|
  endif

  if (Редактировать марку?) then (да)
    |Марка|
    :Изменение данных марки;
    :Сохранение изменений;
    |Клиент|
  endif

  if (Удалить марку?) then (да)
    |Марка|
    :Подтверждение удаления;
    :Удаление марки;
    |Клиент|
  endif
endif

stop
@enduml
