@startuml
start

:Управление марками;
partition "Операции с марками" {
:Добавить марку в коллекцию;
if (Является ли марка редкой? (стоимость > 1000)) then (да)
:Отметить марку как редкую;
else (нет)
:Отметить марку как обычную;
endif
:Удалить марку из коллекции;
}

:Управление коллекциями;
partition "Операции с коллекциями" {
:Группировать коллекции по владельцам;
:Отсортировать владельцев по стоимости коллекции по убыванию;
}

:Управление коллекционерами;
partition "Операции с коллекционерами" {
:Группировать редкие марки по коллекционерам;
:Найти владельца самой дорогой марки;
:Найти коллекционера с максимальным количеством редких марок;
:Отфильтровать коллекционеров, имеющих марки старше 10 лет;
}

stop
@enduml