@startuml
start

partition "Регистрация и аутентификация" {
  if (Пользователь зарегистрирован?) then (нет)
    :Регистрация пользователя;
  else (да)
    :Вход в систему;
  endif
}

partition "Управление коллекциями" {
  :Просмотр коллекций;
  :Создание коллекций;
  :Редактирование коллекций;
  :Удаление коллекций;
}

partition "Управление марками" {
  :Просмотр марок;
  :Создание марок;
  :Редактирование марок;
  :Удаление марок;
}

partition "Просмотр и управление профилем" {
  :Просмотр профиля;
  :Редактирование профиля;
}

stop
@enduml