@startuml
start

partition "Регистрация и аутентификация" {
  if (Пользователь зарегистрирован?) then (нет)
    :Регистрация пользователя;
  else (да)
    :Вход в систему;
  endif
}

partition "Управление коллекциями и марками" {
  :Просмотр коллекций;
  :Редактирование коллекций;
  :Добавление/удаление марок;
}

partition "Просмотр и управление профилем" {
  :Просмотр профиля;
  :Редактирование профиля;
}

stop
@enduml