@startuml
start

partition "Администрирование" {
  if (Пользователь - администратор?) then (да)
    :Управление пользователями;
    :Блокировка пользователя;
    :Редактирование профиля пользователя;
    :Сброс пароля пользователя;
  else (нет)
    :Доступ запрещен;
  endif
}

stop
@enduml
