@startuml
|Клиент|
start

' Регистрация
if (Зарегистрирован?) then (да)
  :Войти;
else (нет)
  :Ввести данные регистрации;
  |Система|
  :Обработать регистрацию;
  if (Успешно?) then (да)
    |Клиент|
    ' Удалено: :Показать подтверждение;
  else (нет)
    :Показать ошибку;
    stop
  endif
endif

' Вход
|Клиент|
:Ввести логин и пароль;
|Система|
:Проверить данные;
if (Успешно?) then (да)
  |Клиент|
  :Открыть профиль;
else (нет)
  :Показать ошибку;
  stop
endif

' Выход
:Нажать "Выход";
|Система|
:Завершить сессию;
|Клиент|
:Вернуться на страницу входа;

stop
@enduml
