@startuml
|Коллекционер|
start
:Попытка входа;
:Ошибка входа;
:Отправка запроса на сброс пароля;
|Админ|
:Получение запроса;
:Поиск пользователя;
:Сброс пароля;
:Отправка нового пароля;
|Коллекционер|
:Получение нового пароля;
:Вход в систему;
stop
@enduml
